set(VERSION_REGEX "([0-9]+)(\\.([0-9]+))?(\\.([0-9]+))?(\\.([0-9]+))?")

macro(split_version_string VER OUTPUT_PREFIX)
	string(REGEX MATCH ${VERSION_REGEX} VERSION_MATCHED "${VER}")
	set(${OUTPUT_PREFIX}_MAJOR ${CMAKE_MATCH_1} PARENT_SCOPE)
	mark_as_advanced(${OUTPUT_PREFIX}_MAJOR)
	set(${OUTPUT_PREFIX}_MINOR ${CMAKE_MATCH_3} PARENT_SCOPE)
	mark_as_advanced(${OUTPUT_PREFIX}_MINOR)
	set(${OUTPUT_PREFIX}_PATCH ${CMAKE_MATCH_5} PARENT_SCOPE)
	mark_as_advanced(${OUTPUT_PREFIX}_PATCH)
	set(${OUTPUT_PREFIX}_TWEAK ${CMAKE_MATCH_7} PARENT_SCOPE)
	mark_as_advanced(${OUTPUT_PREFIX}_TWEAK)
endmacro()
